require 'rake'

module DefaultKeyQuestions
  def self.magic_struct
    [
      { question_title: "Teacher Input/Ownership", key_question: "Identify the model for teacher engagement in the PD design and program execution – whether for program offerings/design (front-end) or as feedback source to on-going program updates (execution), or both.",  points: ['Consider both district/network-wide PD as well as individual school site PD.','Who are the key players currently responsible for designing PD?','Think about whether or not teacher feedback is incorporated into the design and development of PD.','Evidence should include specific examples of how teachers do or do not participate in the development of PD offerings','Example 3 – Defined and Managed: "Although there are no formal roles/rules for teacher participation in PDF, we have teachers in every school who consistently create, update, or deliver PD to other teachers."',]},
      { question_title: "Empowered Teachers", key_question: "Determine level of teacher accountability and choice in PD offerings and personalization.", points: ['Consider outside of the mandated PD offerings, are teachers given the option to choose from a selection of PD offerings?','Consider both district/network wide PD as well as individual school site PD.','Is there support for teachers to attend PD outside of the district offerings?','Evidence should include specific examples of how teachers do or do not participate in the development of PD offerings','Example 1- Non-Existent: "PD is determined for teachers primarily by their principals or by the district based on tenure, content area, district/school initiatives and is not at all based on identified individual professional growth needs."',]},
      { question_title: "Collective/Team Development", key_question: "", points: ['What are the formal structures in place specifically designated for teacher collaboration – professional learning communities, coaching/mentors, etc.?','What processes do we currently have in place to track how time is utilized during these formalized structures?','How do teachers perceive the quality of the collaborative structures to be?','Example 2 – Initial: "All teachers in our district are part of at least one formalized structure (ie. PLC or grade-level meeting), but the quality of work completed is highly variable."',]},
      { question_title: "Identify PD Needs", key_question: "Identify the level of data-driven capability to create PD offerings and personalize teacher PD selections based on needs.", points: ['Consider both the teacher evaluation tool and any other methods you have in place for identifying teacher\'s professional goals. For example, annual review/teacher assignment discussions, teacher interest surveys, informal observations, student outcome/achievement analytics, etc.','Think about whether or not the data generated from the framework is used to identify teacher\'s professional needs and drive future PD.','Once the professional goals have been identified, do you follow up formally to ensure the available PD is aligned with his or her professional needs?',]},
      { question_title: "Develop Personalized PD", key_question: "Identify the level of differentiation among PD offerings – personalization and relevancy to the teacher needs.", points: ['Consider, are all teachers exposed to the same PD regardless of their identified needs?','Differentiation is a teacher\'s or PD tool\'s response to the learners\' needs.','Is there a difference between individual school site PD and district/network wide PD?','Example 3 – Defined and Managed: "All of our teachers have growth/development goals defined each year. We are in the process of purchasing or developing PD content that addresses the majority of these identified PD needs. Currently, we struggle with offering PD for veteran teachers."',]},
      { question_title: "Access Multiple PD Models", key_question: "Further identifies the level of personalization and occasions for teachers to take advantage of PD offerings.", points: ['Think about what types of PD are offered in your program (helpful to list out all current forms of PD being offered) Is there more than one method of delivery?','This question is not asking if you take advantage or access all of the delivery models, just an inventory of what you have available. If it is unclear what is currently available, the product inventory framework (see Data and Technology Diagnostic) might be a good step to complete to provide the needed information – whether as an input to the consensus discussion (if this is a known gap up front) or a follow-up.','This question is a good opportunity for the group to clarify what they consider to be PD – coaching, common planning time, set-aside PD time only (e.g. "Wednesday PD"), etc.','Example 2 – Initial: "All teachers have access to in-person PD lectures, and all teachers work with instructional coaches throughout the school year. Many of our teachers participate in online learning they find on their own, but the district does not provide any digital content."',]},
      { question_title: "Use Continuous Feedback", key_question: "Identifies whether teachers are taking advantage of PD based on on-going feedback and observations to improve teacher performance – or is feedback separate from the PD planning/delivery process?", points: ['Outside of the formal evaluations each year, how much feedback do your teachers\' receive?','What processes are in place to follow-up with a teacher\'s engagement in PD and ensure he or she is making the recommended adjustments?','Is the process consistent for new teachers and more seasoned teachers?','Example 3 – Defined and Managed: "Our teachers receive 3 formal evaluations each year as well as weekly instructional coaching sessions that serve as informal evaluations. Our instructional coaches help identify areas for growth for every teacher and provide support for their development."',]},
      { question_title: "Vision", key_question: "Identifies how PD fits within the broader strategy of leadership within the districts – empower teachers through improved practice.", points: ['"Vision" can be interpreted in a lot of ways and may be a source of contention with the cross-team in the room. The language is ambiguous intentionally to prompt a conversation about a difficult topic.','Example 2 – Initial: "We have a lot of different exciting initiatives roll though our district over the past 10 years. Although each one in itself seemed like a good idea, nothing ever seems connected, and now, our staff and teachers are burned out on all the improvement places. There is a district vision, but not all the initiatives underway are aligned."',]},
      { question_title: "Instructional Leadership", key_question: "Determine the role and involvement of teacher and district leaders of supporting improved teacher practice.", points: ['Consider whether improved instruction is prioritized in terms of leaders\' time spent (e.g. meeting agendas) and how your school/district culture is set up to support improved instruction?','Is the visibility of leaders in the classroom consistent across school sites?',]},
      { question_title: "Change Management", key_question: "Identify the capability maturity for driving whole system redesign initiatives, based on prior initiatives.", points: ['What standard processes do you have in place for managing and leading change?','Consider the level of turnover of leadership positions in central office as a measure of strategic continuity.','Think about specific descriptions of recently undertaken change initiatives, how they were managed, and whether or not they had sustained success.',]},
      { question_title: "Communication", key_question: "Identify the level of capability in building support and executing strategy/leadership through communications.", points: ['Think about whether or not all stakeholders receive the same information? Does it depend on the leader?','How do you measure the extent to which stakeholders buy into initiatives?','Example 2 – Initial: "The central office conducts monthly information and training sessions with all principals in the district. Any new initiatives are presented and discussed during those meetings. Some principals are really good about spreading the information throughout their schools, but other principals are not. Some teachers are taken off guard when a new program begins."',]},
      { question_title: "District Budget Allocation", key_question: "Does the budgeting and planning process allow for the types of spending (personnel, local customization, external vs. internal content, etc.) that is required for the current and future design of PD programs?", points: ['Do you know how your budget is allocated specifically for PD and what percentage is that of the total district operating budget?','Do principals and teachers feel there is enough budget allocated to PD?','How transparent is the budgeting process, and do teachers and principals understand how their annual PD budgets are determined?',]},
      { question_title: "PD Financial Management", key_question: "Identify the level of financial support of PD – and key spending categories – to determine whether funding will need to be reevaluated for planned PD changes.", points: ['Can you retrieve information about PD spending from one centralized place?','Evidence should include description of what data system is used for financial management, the process used in collecting information about budget and actual spending on PD, and an assessment of how well integrated PD budgeting and planning is with the district spending as a whole.',]},
      { question_title: "School Master Schedules", key_question: "Determine whether teachers have appropriate work time to take advantage of PD offerings – whether currently or as part of redesigned program.", points: ['Is there an opportunity to improve teaching and learning by changing master schedules?',]},
      { question_title: "Teacher Time", key_question: "Identify any potential limitations in teacher schedules to teacher professional development objectives.", points: ['Consider time embedded into the school day as well as designated PD days during the summer/before school is in session.','Is teacher prep time regularly taken up?',]},
      { question_title: "Teacher Supports", key_question: "Identify the level of professional development leadership support for individual teacher professional development needs.", points: ['Do all school sites have the equal professional support (e.g. coaches, lead teachers)?','Does the support vary depending on your tenure as a teacher?',]},
      { question_title: "Common Core State Standards", key_question: "Identify the level of program integration and support with CCSS initiatives – curriculum and professional development alignment.", points: ['Example 2 – Initial: "We are in the process of selecting a vendor to provide CCSS-aligned PD content. We plan to integrate this new content in our PD training within the next 2 months."',]},
      { question_title: "Policy Support", key_question: "Identify any potential synergies or gaps in support for professional development with external parties or regulations.", points: ['Consider union time restrictions on PD, district/state policies about master schedules, budget, or other policy items that could impact a PD change initiative.','Also consider internal policies such a procurement permissions, conference allocation permissions, and security policies that could impede innovation in PD redesign.',]},
      { question_title: "PD Digital Platform Capability", key_question: "What is the current level of capability in existing IT infrastructure and are new capabilities required (funding, timeline, etc.) to deliver the desired PD program elements?", points: ['Evidence should include the name of the PD delivery platform and how teachers currently use it.','Is the platform reliable and functional (including speed, content, etc.) in delivering the needed capabilities?','Example 3 – Defined and Managed: "We have been using True North Logic to manage our teacher evaluation data and process for the past 2 years and have recently implemented their PD module. In the next year, we want our teachers to use the TNL portal as a one-stop-shop for evaluation, PD tracking and PD content delivery."',]},
      { question_title: "Ease of Access", key_question: "In support of the offering modes, identify the level of access to digital content/information in light of PD program design objectives.", points: ['Do teachers and other staff complain about access to PD?','Is access the same for all users and is there a single sign-on?','Is there adequate training on how to access digital PD content?','If in-person PD choices are offered, do teachers understand how to choose/access the various offerings?',]},
      { question_title: "Network Availability", key_question: "Is connectivity and network speed appropriate to allow needed access to digital tools, content and information?", points: ['Evidence should include specific data on the number of schools with broadband internet access, laptop/teacher and laptop/student rations, and percent of teachers that access content from home and from work.',]},
      { question_title: "Data Capture", key_question: "Determine what level of data-driven content is possible or needed for the PD redesign objectives.", points: ['Example 1 – Non-Existent: "We collect student data in Powerschool, teacher data in Lawson, and assessment data in Schoolnet. We do not currently track data about PD. We have to log in to each of these systems individually to look at the data."','Example 2 - Defined and Managed: "We collect all of our data in Oracle. Right now, only one analyst in our HR department is able to export data/provide reports when we need them, but we are working on training others to access the data."','Is it clear what data is captured? If not, might be useful to inventory the key data captured (in collaboration with IT) to educate the full PD team and to more accurately evaluate this aspect – whether before or after the readiness assessment process.',]},
      { question_title: "Data Access", key_question: "Is information that helps identify teacher needs, student performance that drives teacher professional development needs or other PD program needs easily obtainable, or is that an area of need as part of the redesign effort?", points: ['Consider emphasis on whether or not teachers are using data to make informed decisions around PD.','Similar to the data captured, is it clear what data is accessible and to whom? Often there is more capability than is known, due to historical lack of adoption or limited training to sustain knowledge in this space. If it is unclear what the current capability is, this might warrant further analysis.',]},
      { question_title: "CCSS Alignment", key_question: "Determine the level of program cohesion and PD integration with curriculum (for relevant PD offerings).", points: ['Think through whether all or only some of the curriculum, assessments and instruction are aligned.',]},
      { question_title: "CCSS Implementation", key_question: "Determines the current level of adoption of CCSS – how will this impact the proposed whole system redesign effort for professional development? Will the timing of this PD redesign help or potentially \"compete\" for resources/focus?", points: ['Are some content teachers further along in the adoption process than others?',]},
      { question_title: "Quality PD Content Availability", key_question: "Is information that helps identify teacher needs, student performance that drives teacher professional development needs or other PD program needs easily obtainable, or is that an area of need as part of the redesign effort?", points: ['Determine your organization\'s definition of high-quality PD. If this has not yet been completed, this might be a good next step.','Is the PD content relevant to teacher\'s identified needs? See earlier section as to how teacher needs are identified, as well as any confidence in the knowledgebase of the team as to the teacher perspective on this question (along with district, principle, PD leads, etc.).','What formal processes do you have in place to measure quality of PD offerings (assessment, impact to student outcomes, teacher PD satisfaction, etc.)?',]},
      { question_title: "PD Content Participation", key_question: "Are current PD offerings used – and if not, what is the barrier to their use? If used, what is the reason that they are? If unknown, potentially a follow-up to learn more before finalizing PD redesign current state assessment.", points: ['Consider what systems you have in place to track teacher participation of available PD.','Is there support/funding to attend PD sessions outside of the school offerings?','This question is about accessing PD content that provided. The next question is about whether organizations track whether/how teachers implement what they learned from PD they have taken.',]},
      { question_title: "PD Content Implementation", key_question: "Determine the level of data-driven processes to understand the level of usage of current offerings and rationale. If immature, might incorporate redesign efforts to improve.", points: ['Do you currently have a system in place to track teacher satisfaction of PD?','Think about how you would determine how PD has influenced teacher\'s practice.','Example 3 – Defined and Managed: "We collect a lot of data about PD needs and consumption using our Teachscape system. This integrates data from multiple sources and shows how teachers are using (or not using) PD content that we are providing. We need to define a process for linking usage of PD back to teacher performance so that we can subsequently update our PD offerings."',]},

    ]
  end

  def self.create
    magic_struct.each do |item|
      question = Question.find_by(headline: item[:question_title])
      key_question = KeyQuestion::Question.create(text: item[:key_question], question: question) 

      item[:points].each do |point|
        KeyQuestion::Point.create(text: point, key_question: key_question)
      end

      puts "Created #{question.headline} key question"
    end
  end

end

namespace :db do
  desc "Create all default key question objects"
  task :create_default_key_questions => :environment do
    ActiveRecord::Base.transaction do
      DefaultKeyQuestions::create()
    end
  end
end
