source 'https://rubygems.org'
ruby '2.5.3'

gem 'bundler', '~> 1.3', '>= 1.3.5'
gem 'rails', '~> 4.2.8'
gem 'actionpack-action_caching'
gem 'activerecord-session_store'
gem 'angular-rails-templates'
gem 'authority'
gem 'bcrypt'
gem 'bootstrap-sass', '3.3.4.1'
gem 'bootstrap3-datetimepicker-rails', '~> 3.1.0'
gem 'carrierwave'
gem 'descriptive-statistics'
gem 'devise_masquerade'
gem 'devise'
gem 'fog'
gem 'font-awesome-rails', '~> 4.7.0.1'
gem 'foundation_emails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'mandrill_mailer'
gem 'mandrill-api'
gem 'mini_magick'
gem 'paranoia'
gem 'pdfkit', '0.6.2'
gem 'pg', '~> 0.21'
gem 'premailer-rails'
gem 'puma'
gem 'rails_admin'
gem 'redactor-rails', '0.5.0'
gem 'sass-rails'
gem 'selectize-rails', '0.12.1'
gem 'sidekiq'
gem 'twitter'
gem 'uglifier', '>= 1.3.0'
gem 'wkhtmltopdf-binary', '0.9.9.3'
gem 'yajl-ruby'
gem 'zurb-ink-rails', '~> 1.0.5'

source 'https://rails-assets.org' do
  gem 'rails-assets-angular-bootstrap', '0.12.1'
  gem 'rails-assets-angular-datatables'
  gem 'rails-assets-angular-file-upload', '~> 1.1.5'
  gem 'rails-assets-angular-moment', '1.0.0.beta.6'
  gem 'rails-assets-angular-redactor', '1.1.4'
  gem 'rails-assets-angular-resource', '1.2.28'
  gem 'rails-assets-angular-route', '1.2.28'
  gem 'rails-assets-angular-sanitize', '1.2.28'
  gem 'rails-assets-angular-shims-placeholder', '0.4.2'
  gem 'rails-assets-angular-tablesort', '~> 1.1.2'
  gem 'rails-assets-angular-ui-router', '0.2.15'
  gem 'rails-assets-angular-ui-utils', '0.2.3'
  gem 'rails-assets-angular', '~> 1.2.0'
  gem 'rails-assets-clipboard', '1.5.10'
  gem 'rails-assets-datatables-buttons', '~>1.0.0'
  gem 'rails-assets-highcharts', '= 3.0.10'
  gem 'rails-assets-jquery', '2.1.4'
  gem 'rails-assets-moment', '2.13.0'
  gem 'rails-assets-rollbar', '1.2.2'
  gem 'rails-assets-underscore', '1.8.3'
end

group :development, :test do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'dotenv-rails'
  gem 'factory_girl_rails', '~> 4.6.0'
  gem 'faker', '~> 1.6.1'
  gem 'foreman'
  gem 'jasmine', '~> 2.5.2'
  gem 'letter_opener_web'
  gem 'letter_opener'
  gem 'pry', '0.10.1'
  gem 'rails-assets-angular-mocks', '1.2.28'
  gem 'rake', '10.5.0'
  gem 'spring-commands-rspec'
  gem 'spring', '~> 1.7.0'
end

group :test do
  gem 'rails-controller-testing'
  gem 'rspec-collection_matchers'
  gem 'rspec-rails', '~> 3.5.2'
  gem 'rspec', '~> 3.5.0'
  gem 'shoulda-matchers', '~> 3.1.1'

  gem 'rspec-sidekiq', '~> 2.2.0'

  gem 'database_cleaner', '~> 1.5.3'
  gem 'rails-assets-karma-runner--karma-ng-html2js-preprocessor', source: 'https://rails-assets.org'
end

group :production do
  gem 'dalli'
  gem 'memcachier'
  gem 'rails_12factor'
  gem 'newrelic_rpm'
end
