json.id data_access_question.id
json.created_at data_access_question.created_at
json.updated_at data_access_question.updated_at
json.data_storage data_access_question.data_storage
json.who_access_data data_access_question.who_access_data
json.how_data_is_accessed data_access_question.how_data_is_accessed
json.why_data_is_accessed data_access_question.why_data_is_accessed
json.notes data_access_question.notes
