json.id data_entry_question.id
json.created_at data_entry_question.created_at
json.updated_at data_entry_question.updated_at
json.who_enters_data data_entry_question.who_enters_data
json.when_data_is_entered data_entry_question.when_data_is_entered
