json.id         @user.id
json.email      @user.email
json.first_name @user.first_name
json.last_name  @user.last_name
json.twitter    @user.twitter
json.created_at @user.created_at
json.updated_at @user.updated_at
json.role       @user.role
json.team_role  @user.team_role
