json.id technical_question.id
json.created_at technical_question.created_at
json.updated_at technical_question.updated_at
json.platforms technical_question.platforms
json.hosting technical_question.hosting
json.connectivity technical_question.connectivity
json.single_sign_on technical_question.single_sign_on

